### ISSUE TITLE
Home assistant

### ISSUE THREAD

**Issue by filoor** [scraton/node-red-contrib-telegrambot-home#4]
Hi im trying to send a Hass.io cam snapshot as image 

i have did the  next 
Method: sendphoto
`{
    "photo": "http://localhost:8123/api/camera_proxy/camera.foscam?token=***************************************************************"
    ,"Caption": "test"
}`

but im getting the next error:

`Unhandled rejection Error: ETELEGRAM: 400 Bad Request: wrong HTTP URL specified
    at request.then.resp (/config/node-red/node_modules/node-telegram-bot-api/src/telegram.js:280:15)
    at tryCatcher (/config/node-red/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/config/node-red/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/config/node-red/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/config/node-red/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/config/node-red/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/config/node-red/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/config/node-red/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/config/node-red/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)`

**Comment by scraton** [comment]
Hi there!

This is most likely an issue of trying to reference a local address for the photo. Telegram is going to try and pull the image on their servers, but it won't be able to access your localhost.

Your best bet to accomplish this would likely be to either upload the image to a publicly accessible endpoint, or send the photo content itself as part of the payload. [Here are the docs](https://github.com/yagop/node-telegram-bot-api/blob/master/doc/usage.md#sending-files) on the available ways to send a photo (also see the [sendPhoto docs](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#TelegramBot+sendPhoto)). You'd probably want to load the photo in a function node and pass it as a `stream.Stream` or `Buffer`.

Let me know if that helps! :)

**Comment by filoor** [comment]
Hi,

Thank you for you quick response.
I have managed to send a local snapshot.
The only problem i face now is  that it's not always send the picture's if i try it 10 times i think it sends it 4 time.
I don't see any error.

**Comment by scraton** [comment]
Would it be possible for you to share the code you’re using to send the image to the telegram node? I assume you are using a function node to construct the payload. Could you provide the source of that? I’d like to try and reproduce the issue on my end so I can diagnose what may be going on.

Thanks! :)

**Comment by filoor** [comment]
i have made a smal flow example
i have changed my chat id an api


`[{"id":"ed2e8a3a.7ad6c8","type":"telegrambot-payload","z":"799b8f75.ba494","name":"stuur foto","bot":"78a80177.ce85f","chatId":"aaaa","sendMethod":"sendPhoto","payload":"{\n    \"photo\": \"/config/tmp/snapshot.jpg\",\n    \"text\": \"Inbreker\"\n}","x":860,"y":360,"wires":[[]]},{"id":"78a80177.ce85f","type":"telegrambot-config","z":"","botname":"example","usernames":"","chatIds":"","pollInterval":"300"}]`

**Comment by scraton** [comment]
Thanks for providing the flow example.

I've been able to re-create the issue. It does indeed appear to work once and then fail on subsequent attempts. The Telegram API is returning an error to node-red's logs:

```
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: there is no photo in the request
    at request.then.resp (/data/node_modules/node-telegram-bot-api/src/telegram.js:280:15)
    at tryCatcher (/data/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/data/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/data/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/data/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/data/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/data/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/data/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/data/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

So it would appear that subsequent sends aren't getting the photo anymore, which is odd considering the payload doesn't change. I will have to do a deeper investigation on this but likely won't have time to get to it until tomorrow. I'll keep you posted!

**Comment by scraton** [comment]
Just kidding, I had time to fix it now since it turned out to be an easy fix.

The static payload was apparently not as static as necessary. It was being modified between node invocations.

The 0.2.2 release should fix your issues. I've issued a request to node-red to update the plugin, so you should see an update in the manage palette section shortly. Thanks for reporting this issue and your help in fixing it! :)

**Comment by filoor** [comment]
Thank you mate it works now
